### ISSUE TITLE
Inconsistent translations on article page

### ISSUE THREAD

**Issue by bodangren** [Reading-Advantage-Thailand/reading-advantage#189]
Localize buttons and titles for consistency.
<img width="1380" alt="image" src="https://github.com/user-attachments/assets/233ec614-bf16-4299-86bb-00259f54e5f2">

**Comment by HyBiTz-dev** [comment]
i update this to live site now

![translations on article page](https://github.com/user-attachments/assets/bb22251b-5f2f-4f14-bfcb-b946cec02d0e)
