### ISSUE TITLE
Localization incomplete on Report page

### ISSUE THREAD

**Issue by bodangren** [Reading-Advantage-Thailand/reading-advantage#190]
Localize table headers for consistency
<img width="1403" alt="image" src="https://github.com/user-attachments/assets/606f1aea-ecd8-4737-87cf-d314e5b5640e">

**Comment by HyBiTz-dev** [comment]
i update this to live site now

![Localization in history](https://github.com/user-attachments/assets/f4089f97-5c9c-4ad0-9fe5-f27ffaedf2d7)
