### ISSUE TITLE
User settings page not localized

### ISSUE THREAD

**Issue by bodangren** [Reading-Advantage-Thailand/reading-advantage#191]
Localize user settings page
Remove "localization tab that links to nowhere
<img width="1386" alt="image" src="https://github.com/user-attachments/assets/91a1829d-ee48-4122-9ba2-99e09e27b062">

**Comment by HyBiTz-dev** [comment]
i remove it and update to live site now

![remove localization ](https://github.com/user-attachments/assets/5e524197-b155-45e5-b6ad-bdf509e18ce0)
