### ISSUE TITLE
Settings page: licensing doesn't function?

### ISSUE THREAD

**Issue by bodangren** [Reading-Advantage-Thailand/reading-advantage#194]
The license section of Settings doesn't seem to work. What is the proposed workflow for admin or teacher giving out licenses?
![image](https://github.com/user-attachments/assets/951c617a-7512-4648-a7bc-450b2c470f34)

**Comment by HyBiTz-dev** [comment]
i working but before in license system page it copy function it copy id license it can't use for activated in setting page.

now i change in license system page copy function it copy key instead it can use activate license. 

![1](https://github.com/user-attachments/assets/b492846b-fefc-47cb-9a32-4ca66207482d)


![2](https://github.com/user-attachments/assets/adbbdd27-c135-498b-aa70-9013e7fe3ada)
